### ISSUE TITLE
Next.js build warnings

### ISSUE THREAD

**Issue by huypham50** [val-town/codemirror-ts#30]
Getting these warnings while `yarn build` Next.js application
```
$ next build
  ▲ Next.js 14.2.3
  - Environments: .env

   Creating an optimized production build ...
 ⚠ Compiled with warnings

./node_modules/@typescript/vfs/dist/vfs.esm.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/@typescript/vfs/dist/vfs.esm.js
./src/frontend/components/CodeEditor/typescriptExtensions.ts
./src/frontend/components/CodeEditor/editor.tsx
./src/frontend/components/CodeEditor/index.tsx

./src/frontend/components/CodeEditor/typescriptExtensions.ts
The generated code contains 'async/await' because this module is using "topLevelAwait".
However, your target environment does not appear to support 'async/await'.
As a result, the code may not run as expected or may cause runtime errors.

Import trace for requested module:
./src/frontend/components/CodeEditor/typescriptExtensions.ts
./src/frontend/components/CodeEditor/editor.tsx
./src/frontend/components/CodeEditor/index.tsx

./node_modules/typescript/lib/typescript.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/typescript/lib/typescript.js
./src/frontend/components/CodeEditor/typescriptExtensions.ts
./src/frontend/components/CodeEditor/editor.tsx
./src/frontend/components/CodeEditor/index.tsx
```

`typescriptExtensions.ts` is basically [this demo on Stackblitz](https://stackblitz.com/edit/vitejs-vite-giwkc3?file=src%2Fmain.ts)

Code editor still works, but I haven't been able to root cause these issues, have anyone seen anything similar?

**Comment by tmcw** [comment]
The error message around async/await is pretty descriptive: using an `await` statement on the top level is something that is [not supported across all browsers](https://caniuse.com/mdn-javascript_operators_await_top_level), and your project is apparently configured to try and support browsers where top-level await isn't supported.

This is from the code in the example, which isn't part of the module proper. You can avoid the top-level await by using old-school `.then()` syntax on the `createDefaultMapFromCDN` call instead of awaiting it.

**Comment by tmcw** [comment]
Closing - these warnings are in application code rather than the module.
